theme: jekyll-theme-minimal
title: Nicola Tamanini
logo: Nicola.jpg
description: Ciao I am Nicola. I come in peace.
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
