theme: jekyll-theme-minimal
title: Nicola Tamanini
logo: assets/img/Nicola.JPG
description: Ciao I am Nicola. I come in peace.
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Homepage
    url: homepage
